# Generated by Django 5.1.1 on 2024-10-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Ref_id',
            new_name='reference',
        ),
    ]
